export const GETCHARACTERSSUCCESS = 'GETCHARACTERSSUCCESS'
export const GETCHARACTERSFAIL = 'GETCHARACTERSFAIL'

export const UPDATEONLINEUSERS = 'UPDATEONLINEUSERS'

export const GETCHARACTERCOUNTSUCCESS = 'GETCHARACTERCOUNTSUCCESS'
export const GETCHARACTERCOUNTFAIL = 'GETCHARACTERCOUNTFAIL'

export const GETTWOCHARACTERSSUCCESS = 'GETTWOCHARACTERSSUCCESS'
export const GETTWOCHARACTERSFAIL = 'GETTWOCHARACTERSFAIL'

export const VOTEFAIL = 'VOTEFAIL'

export const ADDCHARACTERSUCCESS = 'ADDCHARACTERSUCCESS'
export const ADDCHARACTERFAIL = 'ADDCHARACTERFAIL'
export const UPDATENAME = 'UPDATENAME'
export const UPDATEGENDER = 'UPDATEGENDER'
export const INVALIDNAME = 'INVALIDNAME'
export const INVALIDGENDER = 'INVALIDGENDER'

export const GETCHARACTERSUCCESS = 'GETCHARACTERSUCCESS'
export const GETCHARACTERFAIL = 'GETCHARACTERFAIL'
export const REPORTSUCCESS = 'REPORTSUCCESS'
export const REPORTFAIL = 'REPORTFAIL'
