export const GETCHARACTERSUCCESS = 'GETCHARACTERSUCCESS'
export const GETCHARACTERSFAIL = 'GETCHARACTERSFAIL'

export const UPDATEONLINEUSERS = 'UPDATEONLINEUSERS'

export const GETCHARACTERCOUNTSUCCESS = 'GETCHARACTERCOUNTSUCCESS'
export const GETCHARACTERCOUNTFAIL = 'GETCHARACTERCOUNTFAIL'

export const GETTWOCHARACTERSSUCCESS = 'GETTWOCHARACTERSSUCCESS'
export const GETTWOCHARACTERSFAIL = 'GETTWOCHARACTERSFAIL'

export const VOTEFAIL = 'VOTEFAIL'
